require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisitorPassesController do

  # This should return the minimal set of attributes required to create a valid
  # VisitorPass. As you add validations to VisitorPass, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisitorPassesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all visitor_passes as @visitor_passes" do
      visitor_pass = VisitorPass.create! valid_attributes
      get :index, {}, valid_session
      assigns(:visitor_passes).should eq([visitor_pass])
    end
  end

  describe "GET show" do
    it "assigns the requested visitor_pass as @visitor_pass" do
      visitor_pass = VisitorPass.create! valid_attributes
      get :show, {:id => visitor_pass.to_param}, valid_session
      assigns(:visitor_pass).should eq(visitor_pass)
    end
  end

  describe "GET new" do
    it "assigns a new visitor_pass as @visitor_pass" do
      get :new, {}, valid_session
      assigns(:visitor_pass).should be_a_new(VisitorPass)
    end
  end

  describe "GET edit" do
    it "assigns the requested visitor_pass as @visitor_pass" do
      visitor_pass = VisitorPass.create! valid_attributes
      get :edit, {:id => visitor_pass.to_param}, valid_session
      assigns(:visitor_pass).should eq(visitor_pass)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VisitorPass" do
        expect {
          post :create, {:visitor_pass => valid_attributes}, valid_session
        }.to change(VisitorPass, :count).by(1)
      end

      it "assigns a newly created visitor_pass as @visitor_pass" do
        post :create, {:visitor_pass => valid_attributes}, valid_session
        assigns(:visitor_pass).should be_a(VisitorPass)
        assigns(:visitor_pass).should be_persisted
      end

      it "redirects to the created visitor_pass" do
        post :create, {:visitor_pass => valid_attributes}, valid_session
        response.should redirect_to(VisitorPass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visitor_pass as @visitor_pass" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorPass.any_instance.stub(:save).and_return(false)
        post :create, {:visitor_pass => {}}, valid_session
        assigns(:visitor_pass).should be_a_new(VisitorPass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorPass.any_instance.stub(:save).and_return(false)
        post :create, {:visitor_pass => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visitor_pass" do
        visitor_pass = VisitorPass.create! valid_attributes
        # Assuming there are no other visitor_passes in the database, this
        # specifies that the VisitorPass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VisitorPass.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => visitor_pass.to_param, :visitor_pass => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested visitor_pass as @visitor_pass" do
        visitor_pass = VisitorPass.create! valid_attributes
        put :update, {:id => visitor_pass.to_param, :visitor_pass => valid_attributes}, valid_session
        assigns(:visitor_pass).should eq(visitor_pass)
      end

      it "redirects to the visitor_pass" do
        visitor_pass = VisitorPass.create! valid_attributes
        put :update, {:id => visitor_pass.to_param, :visitor_pass => valid_attributes}, valid_session
        response.should redirect_to(visitor_pass)
      end
    end

    describe "with invalid params" do
      it "assigns the visitor_pass as @visitor_pass" do
        visitor_pass = VisitorPass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorPass.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor_pass.to_param, :visitor_pass => {}}, valid_session
        assigns(:visitor_pass).should eq(visitor_pass)
      end

      it "re-renders the 'edit' template" do
        visitor_pass = VisitorPass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorPass.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor_pass.to_param, :visitor_pass => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visitor_pass" do
      visitor_pass = VisitorPass.create! valid_attributes
      expect {
        delete :destroy, {:id => visitor_pass.to_param}, valid_session
      }.to change(VisitorPass, :count).by(-1)
    end

    it "redirects to the visitor_passes list" do
      visitor_pass = VisitorPass.create! valid_attributes
      delete :destroy, {:id => visitor_pass.to_param}, valid_session
      response.should redirect_to(visitor_passes_url)
    end
  end

end
